### ISSUE TITLE
Failed to run `yarn bazel run server -- -- -storage_path="/tmp`

### ISSUE THREAD

**Issue by sarsanaee** [google/schedviz#35]
Hi

I'm trying to run the server. However, I'm facing the following error,
```
alireza@neat:~/schedviz$ yarn bazel run server -- -- -storage_path=/tmp/traces_sched
yarn run v1.22.15
warning From Yarn 1.0 onwards, scripts don't require "--" for options to be forwarded. In a future version, any explicit "--" will be forwarded as-is to the scripts.
$ /home/alireza/schedviz/node_modules/.bin/bazel run server -- -storage_path=/tmp/traces_sched
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Writing tracer profile to '/home/alireza/.cache/bazel/_bazel_alireza/3623e6f5b3c7c23c7952e987fbc7cddc/command.profile.gz'
INFO: Call stack for the definition of repository 'llvm_toolchain' which is a llvm_toolchain (rule definition at /home/alireza/.cache/bazel/_bazel_alireza/3623e6f5b3c7c23c7952e987fbc7cddc/external/com_grail_bazel_toolchain/toolchain/rules.bzl:24:18):
 - /home/alireza/schedviz/WORKSPACE:66:1
WARNING: Download from https://releases.llvm.org/9.0.0/clang%2Bllvm-9.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz failed: class java.io.IOException Read timed out
ERROR: An error occurred during the fetch of repository 'llvm_toolchain':
   Traceback (most recent call last):
	File "/home/alireza/.cache/bazel/_bazel_alireza/3623e6f5b3c7c23c7952e987fbc7cddc/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 101
		_download_llvm_preconfigured(rctx)
	File "/home/alireza/.cache/bazel/_bazel_alireza/3623e6f5b3c7c23c7952e987fbc7cddc/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 135, in _download_llvm_preconfigured
		rctx.download_and_extract(urls, sha256 = _llvm_distributions...], ..."))])
java.io.IOException: Error downloading [https://releases.llvm.org/9.0.0/clang%2Bllvm-9.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz] to /home/alireza/.cache/bazel/_bazel_alireza/3623e6f5b3c7c23c7952e987fbc7cddc/external/llvm_toolchain/clang%2Bllvm-9.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz: Read timed out
ERROR: no such package '@llvm_toolchain//': Traceback (most recent call last):
	File "/home/alireza/.cache/bazel/_bazel_alireza/3623e6f5b3c7c23c7952e987fbc7cddc/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 101
		_download_llvm_preconfigured(rctx)
	File "/home/alireza/.cache/bazel/_bazel_alireza/3623e6f5b3c7c23c7952e987fbc7cddc/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 135, in _download_llvm_preconfigured
		rctx.download_and_extract(urls, sha256 = _llvm_distributions...], ..."))])
java.io.IOException: Error downloading [https://releases.llvm.org/9.0.0/clang%2Bllvm-9.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz] to /home/alireza/.cache/bazel/_bazel_alireza/3623e6f5b3c7c23c7952e987fbc7cddc/external/llvm_toolchain/clang%2Bllvm-9.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz: Read timed out
ERROR: no such package '@llvm_toolchain//': Traceback (most recent call last):
	File "/home/alireza/.cache/bazel/_bazel_alireza/3623e6f5b3c7c23c7952e987fbc7cddc/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 101
		_download_llvm_preconfigured(rctx)
	File "/home/alireza/.cache/bazel/_bazel_alireza/3623e6f5b3c7c23c7952e987fbc7cddc/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 135, in _download_llvm_preconfigured
		rctx.download_and_extract(urls, sha256 = _llvm_distributions...], ..."))])
java.io.IOException: Error downloading [https://releases.llvm.org/9.0.0/clang%2Bllvm-9.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz] to /home/alireza/.cache/bazel/_bazel_alireza/3623e6f5b3c7c23c7952e987fbc7cddc/external/llvm_toolchain/clang%2Bllvm-9.0.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz: Read timed out
INFO: Elapsed time: 165.951s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Thanks,
Alireza

**Comment by sarsanaee** [comment]
I think it was a nodejs issue! I upgraded to a newer node.js and it worked!

It seems there is also another dependency to be added which is `libncurses5` I guess.
