### ISSUE TITLE
Can't install on rocky linux 8.6

### ISSUE THREAD

**Issue by JonKohler** [google/schedviz#41]
As the title suggests, I was unable to easily get this setup on Rocky 8.6. I did the clone, and yarn install and that worked, but trying to get the server up fails almost immediately with the following:

```
INFO: Call stack for the definition of repository 'llvm_toolchain' which is a llvm_toolchain (rule definition at /root/.cache/bazel/_bazel_root/116cb4b37cb5ae33998452196fe24c90/external/com_grail_bazel_toolchain/toolchain/rules.bzl:24:18):
 - /root/git/schedviz/WORKSPACE:66:1
ERROR: An error occurred during the fetch of repository 'llvm_toolchain':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/116cb4b37cb5ae33998452196fe24c90/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 101
                _download_llvm_preconfigured(rctx)
        File "/root/.cache/bazel/_bazel_root/116cb4b37cb5ae33998452196fe24c90/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 120, in _download_llvm_preconfigured
                fail(("Failed to detect host OS versi...)))
Failed to detect host OS version: 

Unsupported linux distribution and version: rocky, 8.6
ERROR: no such package '@llvm_toolchain//': Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/116cb4b37cb5ae33998452196fe24c90/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 101
                _download_llvm_preconfigured(rctx)
        File "/root/.cache/bazel/_bazel_root/116cb4b37cb5ae33998452196fe24c90/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 120, in _download_llvm_preconfigured
                fail(("Failed to detect host OS versi...)))
Failed to detect host OS version: 

Unsupported linux distribution and version: rocky, 8.6
ERROR: no such package '@llvm_toolchain//': Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/116cb4b37cb5ae33998452196fe24c90/external/com_grail_bazel_toolchain/toolchain/internal/configure.bzl", line 101
                _download_llvm_preconfigured(rctx)
        File "/root/.cache/bazel/_bazel_root/116cb4b37cb5ae33998452196fe24c90/external/com_grail_bazel_toolchain/toolchain/internal/llvm_distributions.bzl", line 120, in _download_llvm_preconfigured
                fail(("Failed to detect host OS versi...)))
Failed to detect host OS version: 

Unsupported linux distribution and version: rocky, 8.6
```

**Comment by sabarabc** [comment]
Try setting the [distribution flag](https://github.com/grailbio/bazel-toolchain/blob/89adaac1010e5f64ab13662af7f1fe2ca0da4323/toolchain/rules.bzl#L30-L36) to "clang+llvm-9.0.0-x86_64-pc-linux-gnu.tar.xz" here:
https://github.com/google/schedviz/blob/5fb1be3005fb7dbd46fce7bd2ab3813f7131458d/WORKSPACE#L66-L69

The problem is that the llvm_toolchain dependency can't detect your distro, so you have to manually specify the version to download.
